"""Minimal OpenAI-compatible Agent generated by ATK new Agent."""

from __future__ import annotations

import logging
import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except ModuleNotFoundError:
    load_dotenv = None

if load_dotenv is not None:
    load_dotenv()

DEFAULT_BASE_URL = "https://api.openai.com/v1"
SPEC_PATH = Path(".atk/specs/agent_spec.md")
LOGGER = logging.getLogger("atk.generated_agent")


class AgentConfigurationError(RuntimeError):
    """Raised when the generated Agent is missing required runtime configuration."""


def _require_env(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise AgentConfigurationError(f"Missing {name}. Copy .env.example to .env, set {name}, then rerun the Agent.")
    return value


def _load_agent_spec() -> str:
    if not SPEC_PATH.exists():
        raise AgentConfigurationError(
            "Missing .atk/specs/agent_spec.md. Rerun ATK new Agent from the project root before using this Agent."
        )
    try:
        return SPEC_PATH.read_text(encoding="utf-8")
    except OSError as exc:
        raise AgentConfigurationError(f"Unable to read .atk/specs/agent_spec.md: {exc}") from exc


def _format_input(input_data: dict[str, str]) -> str:
    if not input_data:
        return "(empty input)"
    return "\n".join(f"{key}: {value}" for key, value in input_data.items())


def _input_log_context(input_data: dict[str, str]) -> str:
    input_fields = ",".join(input_data) if input_data else "(none)"
    input_char_count = sum(len(str(value)) for value in input_data.values())
    atk_id = input_data.get("atk_id", "").strip() or "(unknown)"
    return f"atk_id={atk_id} input_fields={input_fields} input_char_count={input_char_count}"


def run_agent(input_data: dict[str, str]) -> str:
    """Run the generated Agent for one dataset row or CLI input."""
    log_context = _input_log_context(input_data)
    LOGGER.info("event=agent_run_start %s", log_context)
    try:
        api_key = _require_env("OPENAI_API_KEY")
        model = _require_env("OPENAI_MODEL")
        base_url = os.getenv("OPENAI_BASE_URL", DEFAULT_BASE_URL).strip() or DEFAULT_BASE_URL
        agent_spec = _load_agent_spec()

        from openai import OpenAI

        client = OpenAI(api_key=api_key, base_url=base_url)
        user_input = _format_input(input_data)

        response = client.chat.completions.create(
            model=model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are the initial Agent generated by Agent Tune Kit. "
                        "Follow the project spec, keep the output concise, and return only the answer."
                    ),
                },
                {
                    "role": "user",
                    "content": f"Agent spec:\n{agent_spec}\n\nInput:\n{user_input}",
                },
            ],
        )
        output = response.choices[0].message.content or ""
    except Exception:
        LOGGER.exception("event=agent_run_error %s", log_context)
        raise
    LOGGER.info("event=agent_run_complete %s output_char_count=%s", log_context, len(output))
    return output
