[project]
name = "atk-generated-agent"
version = "0.1.0"
description = "Minimal OpenAI-compatible Agent generated by Agent Tune Kit"
requires-python = ">=3.11"
dependencies = [
  "openai>=1.0.0",
  "python-dotenv>=1.0.0",
]

